### ISSUE TITLE
Set up linter

### ISSUE THREAD

**Issue by mbreton** [js-republic/SGR#3]
We need a code Linter to ensure all contributors have the same code style.

Eslint, is already installed. Which preset we choose ? Airbnb preset, JavaScript Standard, another ?

**Comment by VincentCordobes** [comment]
The *Airbnb preset*  is quite good IMHO. It is the most popular and very strict (maybe too much ?)
We *can* use it as a base and override rules that we find out to be too restrictive.

**Comment by PierrickGT** [comment]
I would also choose the Airbnb preset to lint our project.

**Comment by mbreton** [comment]
So we have to : 

- [ ] Add the eslintrc

- [ ] Update the contributing.md file to explain which code style rules we follow

Who take the point
